name: 'Deploy Yak'
description: 'Deploys a yak package to the McNeel server'
inputs:
  package-name:
    description: 'The package name'
    required: true
  token:
    description: 'The YAK Auth token'
    required: true
  build-path:
    description: 'The Build Directory for the Package'
    required: true
  publish:
    description: 'Publish'
    required: false
    default: ''
  platform:
    description: 'The Platform for the Package'
    required: false
    default: 'win'
branding:
  icon: 'package'
  color: 'yellow'
    
outputs:
  result:
    description: 'Was the upload succesful?'
    value: true
runs:
  using: "composite"
  steps:

    - uses: actions/setup-python@v4
      with:
        cache: 'pip'

    - name: Setup Python
      shell: null
      run : |
        pip install wget

    - name: Cache Yak
      id: cache-yak
      uses: actions/cache@v3
      with:
        path: 'yak.exe'
        key: yak-exe

    # https://discourse.mcneel.com/t/github-action-to-yak/120815/2
    - name: Download Yak
      shell: null
      if: steps.cache-yak.outputs.cache-hit != 'true'
      run: python ${{ github.action_path }}\py\download-yak.py

    - name : Enable Yak exe on Unix
      if: runner.os != 'Windows'
      shell: bash
      run: chmod +x yak.exe

    - name: Build Package(s)
      shell: null
      run: python ${{ github.action_path }}\py\build-package.py -b inputs.buildpath

    - name : Upload Yak(s)
      shell: null
      run: python ${{ github.action_path }}\py\upload-yak.py -p inputs.publish -b inputs.buildpath
